---
title: "Sobre"
description: |
  Blog para discussão e implementação no software R de análise de dados aplicada à auditoria.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Olá!**

Eu sou o Marcos. Sejam bem vindo(a)s!

Neste site você vai encontrar 
Eu vou compartilhar com vocês algumas coisas que venho estudando e tentando aplicar ao longo dos anos do meu trabalho com auditoria.

Já tem mais de 20 anos que trabalho com auditoria do setor público no Tribunal de Contas de Estado do Rio de Janeiro - TCERJ e tenho, mais recentemente, utilizado o R de forma bem satisfatória como uma ferramenta para auxiliar na análise de dados, tarefa cada vez mais necessária neste trabalho.

Meu objetivo aqui é mostrar não só o uso do R mas também algumas técnicas de análisee de dados que podem ser implementadas utilizando essa ferramente, tendo sempre que possível o contexto de auditoria como pano de fundo.

Temos então o seguinte tripé: 

* área de aplicação [auditoria];    
* técnicas [análise de dados] e    
* tecnologia [R e pacotes]

Existem diversas opções para auditor quando se trata de realizar análise de dados em auditoria, mas espero mostrar que o R oferece um amplo leque de opções que o tornam uma escolha bem interessante.

No mais, moro no Rio de Janeiro, sou casado com a Lucianny, pai da Carol e de um _pug_ chamado Froid. 

Espero que gostem deste lugar e que ele traga alguma inspiração e motivação para que você inicie ou aprofunde seus estudos e que seja útil pra vocês! Abs.


