---
title: "Teses da Rutgers"
description: |
  Teses de doutoramento da Universidade Rutgers que tratam da aplicação de análise de dados em auditoria.
author:
  - name: Marcos F. Silva
    url: {}
date: 01-25-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---

A universidade de Rutgers é um forte centro de pesquisa no uso das modernas técnicas de mineração de dados em auditoria financeira e ao longo dos anos diversas teses de doutoramento foram produzidas abordando tópicos de análise de dados em auditoria.

O uso de análise de dados ou métodos quantitativos ou _machine learning_ em auditoria tem sido apresentado com a denominação de `Audit Analytics` e um breve resumo e introdução a esta disciplina pode ser consultado no seguinte link: <http://raw.rutgers.edu/docs/fraud/7fraud/Audit%20Analytics--ISACA.pdf>

Em razão da escassez de material sobre sobre esse tema, listo abaixo algumas das teses que tratam da temática **Análise de Dados em Auditoria** as quais estão disponíveis para _download_ e podem ser obtidas no seguinte link: <https://rucore.libraries.rutgers.edu/>


Titulo                                                   | Autor | Ano de Produção
---------------------------------------------------------|-------|----------------
Cluster Analysis for Anomaly Detection in Accounting |  Sutapat Thiprungsri |  Jan. 2011
Predictive Audit Analytics: Evolving to a New Era | Siripan Kuenkaikaew | Out. 2013
The Application of Exploratory Data Analytis in Auditing | Qi Liu | Out. 2014
The Application of Data Visualization in Auditing        | Abdullah Alawaddhi | Mai. 2015
Developing Automated Applications for Clustering and Outlier Detection: Data Mining Implications for Auditing Practice | Paul Eric Byrnes | Out 2015
Analytics with Exception Prioritization, Consumer Search Volume, and Social Capital | Pei Li | Mai. 2016
Auditing in Environments of Diverse Data |  Basma Moharram | Out. 2016
Three Essays on Audit Technology: Audit 4.0, blockchain, and Audit App | Jun Dai |  Out. 2017 
Public Auditing, Analytics, and Big Data in the Modern Economy | Deniz Appelbaum | Mai., 2017
Designing Continuous Audit Analytics and Fraud Prevention Systems Using Emerging Technologies |  Yunsen Wang |  Mai. 2018
Exploring New Audit Evidence: The Application of Process Mining in Auditing | Tiffany Chiu | Mai. 2018  
Deep Learning Applications in Audit Decision Making |  Ting Sun | Mai. 2018  
Three Essays on Emerging Technologies in Accounting | Feiqi Huang | Jan. 2019  
Three Essays on Audit Innovation: Using Social Media Information and Disruptive Technologies to Enhance Audit Quality |   Andrea M. Rozario | Mai. 2019 
Applying Textual Analysis to Auditing |  Yue Liu | Mai. 2019  
Three Essays on Open Government Data and Data Analytics | Zamil S. Alzamil | Mai. 2019 
Audit Focused Process Mining: The Evolution of Process Mining and Internal Control | Abddulrahman Alrefai | Mai. 2019
Three Essays on the Adoption and Application of Emerging Technologies in Accounting |  Zhaokai Yan | Out. 2019  



Espero que gostem! Boa leitura!

