---
title: "Audit Analytics"
description: |
  Neste _post_ meu objetivo é falar um pouco sobre o que é _Audit Analytics_ e onde encontrar material para estudo.
author:
  - name: Marcos F. Silva
    url: {}
date: 01-31-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
draft: false
---

# O que é _Audit Analytics_?

O uso de análise de dados ou métodos quantitativos ou _machine learning_ em auditoria tem sido apresentado com a denominação de _Audit Analytics_ ou _Audit Data Analytics_ e um breve resumo e introdução a esta 'disciplina' pode ser consultado [neste documento](http://raw.rutgers.edu/docs/fraud/7fraud/Audit%20Analytics--ISACA.pdf) produzido pela Escola de Negócios da Universidade de Rutgers em 2013.

O documento inicia declarando que "*Audit analytics é o uso da tecnologia de análise de dados em Auditoria*". Depois, complementa informando que "*Audit analytics é o processo de identificar, colher, validar, analisar e interpretar várias formas de dados dentro de uma organização para ajudar no desenvolvimento do propósito e missão da auditoria*." 

Também é interessante elencar as possíveis aplicações da _Audit Analytics_ no processo de auditoria, ainda segundo o documento em referência:

* Revisão analítica;    
* Avaliação e testes de controles;
* Testes substantivos;    
* Detecção de fraudes;   
* Análises em geral e produção de relatórios;    
* Transações financeiras e não financeiras.

O `Guide to Audit Data Analytics` da AICPA apresenta uma 'definição' de Audit Data Analytics (ADA) da qual gosto muito e que está no artigo **Reimagining Auditing in a Wired World** de autoria de Paul Byrnes e outros .

De acordo com os autores do artigo `Audit Data Analytics` é "*a ciência e a arte de descobrir e analisar padrões, identificar anomalias e extrair outras informações úteis de dados subjacentes ou relacionados a um objeto de auditoria através de análise, modelagem ou visualização com o objetivo de planejar ou realizar a auditoria*."    

Ainda de acordo com o Guia,  a `ADA` "*são __técnicas__ que que podem ser usadas para realizar vários __procedimentos de auditoria__ incluindo __elementos de avaliação de risco__, __testes de controles__, __procedimentos substantivos__ (isto é, testes de detalhes ou procedimentos analíticos substantivos),ou procedimentos de fechamento de auditoria. ADAs e procedimentos analíticos estão interrelacionados mas nem todas as ADAs são procedimentos analíticos*."

As definições acima remetem a algumas ideias que me parecem centrais para o entendimento do que seja _Audit Analytics_. 

No documento da Rutgers essas ideias aparecem bem explícitas na definição, que é o uso de **tecnologia**, para realizar **análise de dados** na área de **auditoria**.  


Na definição contida no artigo de Byrnes et all, aparecem as ideias de "descobrir e analisar padrões", "identificar anomalias", "extrair outras informações úteis de dados", "através de análise, modelagem ou visualização" que estão associadas a **análise de dados** e, como decorrência, a todo o conhecimento técnico relacionado a essa área do conhecimento.

Os dados objeto de análise são aqueles "subjacentes ou relacionados a um objeto de auditoria" com o objetivo de "planejar ou realizar a auditoria", que fala da área de conhecimento na qual a análise de dados será aplicada, a **auditoria**. Também aqui, existe um corpo de conhecimento específico com o qual os profissionais oriundos das ciências contábeis estão mais familiarizados.    

Nessa definição não há menção a nada que remeta à **tecnologia**. Mas me parece claro que essa omissão talvez tenha relação com o fato de que as tecnologias são passageiras, a todo momento estão surgindo novas e melhores ferramentas capazes de realizar a análise dos dados de forma satisfatória.


A definição do Guia da AICPA faz alusão ao conceito de análise de dados ao associar a _Audit Analytic_ a um conjunto de técnicas e enfatiza bastante a área de aplicação, ao detalhar onde na auditoria podem ser utilizadas.

Também aqui não há menção à tecnologia. O foco da definição está nas áreas de aplicação e faz todo o sentido que assim seja, visto que o objetivo do Guia é, declaradamente, "*fornecer uma introdução e visão geral às técnicas de análise de dados para auxiliar os __auditores de demonstrações financeiras__ na aplicação dessas técnicas durante realização de uma auditoria*".

Como pode ser visto, o Guia da AICPA é direcionado a auditores, auditores de demonstrações financeiras, os quais usualmente são contadores cuja formação, ao menos aqui no Brasil, é deficiente em análise de dados e uso de tecnologia. Não é incomum que os livros texto nacionais de auditoria ainda ensinem a executar testes de auditoria utilizando papel colunado!

Para esse público, o interesse está em saber como essas técnicas podem ser incorporadas em seu trabalho, quais são as vantagens, quais são os custos de adoção e desvantagens. 

Nesse _site_, o meu foco será a implementação prática das técnicas de análise de dados em auditoria, utilizando como tecnologia o ambiente R. Não é meu objetivo discutir conceitos de auditoria financeira ou de qualquer outro tipo de auditoria. Para quem quiser conhecer esses conceitos recomento o [Manual de Auditoria Financeira do TCU](https://portal.tcu.gov.br/biblioteca-digital/manual-de-auditoria-financeira.htm).

Uma questão que pode surgir é: que técnicas de análise de dados são essas?

Elas variam desde as técnicas mais básicas então conhecidas por Técnicas de Auditoria Assistidas por Computador - TAACs até as modernas técnicas de mineração de dados passando por visualização de dados.

Sem a pretensão de ser exaustivo, elenco a seguir algumas técnicas citadas na literatura como utilizadas em trabalhos de auditoria: 

**Técnicas de Auditoria Assistidas por Computador - TAACs**: estatistica descritiva, distribuição de frequencias e tabulação cruzada, sumarização, estratificação, análise de tendências, _Aging_, teste de duplicidade e gaps, lei de Benford, amostragem de auditoria, etc.

**Visualização de Dados**:histograma, diagrama de dispersão, gráfico de linhas, gráfico de barras (simples, empilhados e justapostos), boxplot, etc.

**Técnicas Preditivas (aprendizado supervisionado)**: regressão (simples, múltipla, logística), árvores de decisão, máquinas de vetor suporte, etc.

**Técnicas Descritivas/Exploratórias (aprendizado não supervisionado)**: regras de associação, análise de cluster, análise de componentes principais, análise de redes sociais, mineração de texto, mineração de processos, etc.   
* etc.

# A Análise de Dados Aplicada à Auditoria Hoje

Na introdução do livro **Audit Analytics in the Financial Industry** Jun Dai e Miklos Vasarhelyi colocam a seguinte questão: `O que é Audit Analytics?`  

<aside>

Este livro é uma coletânea de artigos editada por Jun Dai, Miklos A. Vasarhelyi e Ann F. Medinets,  publicado em 2019.

</aside>

Os autores observam que a tecnologia emergente da _Audit Analytics_ (AA) vem sendo cada vez mais utilizada pelos auditores para extrair e processar dados oriundos de uma variedade de fontes para identificação de risco, coleta de evidências e, em última análise, dar suporte à tomada de decisão. 

Atualmente estão acessíveis aos auditores além dos dados oriundos dos sistemas contábeis dos clientes, dados públicos como os disponibilizados nas mídias sociais e na internet de modo geral, dados abertos governamentais, dados climáticos e dados oriundos da 'internet das coisas' (IoT).

O auditor moderno não pode, e não deve, ficar limitado aos dados internos produzidos pela entidade auditada.

Os autores chamam a atenção para o seguinte fato: "Os procedimentos analíticos tradicionais se baseiam fortemente em amostragens dos dados relacionados à auditoria. Não obstante, à medida que os sistemas de ERP estão rapidamente crescendo em popularidade entre as empresas, evidência suficiente não pode mais ser colhida apenas de uma amostra de dados. A _Audit Analytics_ aumenta a população testada de amostras limitadas (subjetiva ou estatística) para milhões de transações na testagem de toda a população o que amplia a cobertura da auditoria de um pequeno percentual das transações para toda a população."

Os autores vêem a _Audit Analytics_ como sucessora dos procedimentos analíticos que já a bastante tempo vem sendo utilizados pelos auditores externos como técnica para o planejamento, testes substantivos e fase de conclusão de auditoria. 

Considerando que os procedimentos analíticos realizados na fase de planejamento da auditoria tipicamente usam dados agregados em alto nível os resultados obtidos com estes procedimentos fornecem apenas indicação geral inicial sobre a existência de erros materiais.

Por outro lado as técnicas de AA  podem ser utilizadas em dados ao nível de transações visto que estas técnicas mantém boa performance ainda quando utilizadas em grandes bases de dados e bases com alta dimensionaliade.

Como resultado a AA pode aumentar a acurácia da avaliação de riscos e melhorar a qualidade do planejamento da auditoria.  

Em um artigo de **2003** chamado `Audit at a Crossroads`, Conan C. Albrech, em vista dos então recentes escândalos de fraude ocorridos em empresas como Enron, WorldCom, Homestore, Quest, Global Crossing, Adelphia, Xerox, Waste Management, Sunbeam e outras, que colocaram a atividade de auditoria independente em xeque e do claro _gap_ de expectativa existente entre o que os auditores afirmam ser sua responsabilidade e o que os usuários das informações contábeis acreditam ser o produto de seu trabalho, já chamava a atenção para a necessidade de uma revisão no modelo de auditoria com vistas a focar na fraude de demostrações financeiras, propondo duas grandes modificações: **análise de toda a população** e **detecção de fraude pró-ativa**. 

Na visão do autor, existe uma necessidade de que métodos estatísticos e tecnológicos sejam inseridos no processo de auditoria com vistas a focar nas fraudes de demonstrações financeiras e para isso propõe as duas modificações acima elencadas.

Essa proposição assenta no entendimento do autor de que "*a disponibilidade de tecnologia e dados em formato digital torna possível realizar rotinas de mineração de dados de formas que historicamente tem sido muito custosa ou mesmo impossível.*" 

Destaco que a aplicação de técnicas de mineração de dados na detecção de fraudes tem sido tão bem sucedida que uma disciplina própria chamada _Fraud Analytics_ vem se desenvolvendo e ganhando cada vez mais espaço.


# Vantagens da _Audit Analytics_

Voltando ao artigo de Jun Dai e Miklos Vasarhelyi, as tecnologias emergentes de análise de dados possuem a capacidade de explorar vastas quantidades de dados em várias estruturas e formatos que não podem ser manipulados pelos procedimentos analíticos tradicionais.

Como vantagens da AA sobre as técnicas mais tradicionais os autories citam: (1) _audit data analytics_ tem um melhor custo benefício em termos de coleta de evidências, (2) muitas das técnicas de análise de dados são escaláveis, isto é, em geral ainda mantém boa performance quando trabalham com grandes quantidades de dados com alta dimensionalidade (muitas variáveis) e (3) algumas técnicas de AA também possuem a habilidade de identificar padrões nos dados com o uso de técnicas não supervisionadas, o que dispensa a necessidade de dados 'rotulados' (variáveis alvo) no conjunto de dados. 


# Material para Estudo

Infelizmente não há muito material de estudo em português sobre o tema _Audit Data Analytics_, mas em inglês já é possível encontrar alguns materiais interessantes.  

**Livros**

Ainda são poucos os livros dedicados ao assunto. Listo a seguir os que conheço:

* [Audit Analytics in the Financial Industry](https://www.amazon.com.br/Analytics-Financial-Industry-Rutgers-Accounting-ebook/dp/B07V9F1RVP)    
* [Audit Analytics and Continuous Audit - Looking Toward the Future](https://www.aicpa.org/content/dam/aicpa/interestareas/frc/assuranceadvisoryservices/downloadabledocuments/auditanalytics-lookingtowardfuture.pdf) Coletânea de artigos disponível para _download_.   
* [Guide to Audit Data Analytics](https://www.amazon.com.br/Guide-Audit-Data-Analytics-AICPA/dp/1945498641/ref=sr_1_1?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=guide+to+audit+data+analytics&qid=1611660592&s=digital-text&sr=1-1-catcorr)
* [Audit Analytics - Data Science for the Accounting Profession](https://www.springer.com/gp/book/9783030490904)    
* [Basic Audit Data Analytics with R](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3142207)
* [Data analytics for internal auditors](https://www.amazon.com.br/Analytics-Internal-Auditors-Audit-English-ebook/dp/B06XPMKDZ2) 
* [Data Analytics: Elevating Internal Audit's Value](https://www.amazon.com/Analytics-Elevating-Internal-Stippich-Bradley/dp/0894139649)   


**Teses e Dissertações**

A universidade de Rutgers é um forte centro de pesquisa no uso das modernas técnicas de mineração de dados em auditoria financeira e ao longo dos últimos anos diversas teses de doutoramento foram produzidas abordando a aplicação de análise de dados em auditoria.

Listo abaixo algumas das teses que tratam da temática **Análise de Dados em Auditoria** as quais estão disponíveis para _download_ e podem ser obtidas no seguinte link: <https://rucore.libraries.rutgers.edu/>


Titulo                                                   | Autor | Ano de Produção
---------------------------------------------------------|-------|----------------
Cluster Analysis for Anomaly Detection in Accounting |  Sutapat Thiprungsri |  Jan. 2011
Predictive Audit Analytics: Evolving to a New Era | Siripan Kuenkaikaew | Out. 2013
The Application of Exploratory Data Analytis in Auditing | Qi Liu | Out. 2014
The Application of Data Visualization in Auditing        | Abdullah Alawaddhi | Mai. 2015
Developing Automated Applications for Clustering and Outlier Detection: Data Mining Implications for Auditing Practice | Paul Eric Byrnes | Out 2015
Analytics with Exception Prioritization, Consumer Search Volume, and Social Capital | Pei Li | Mai. 2016
Auditing in Environments of Diverse Data |  Basma Moharram | Out. 2016
Three Essays on Audit Technology: Audit 4.0, blockchain, and Audit App | Jun Dai |  Out. 2017 
Public Auditing, Analytics, and Big Data in the Modern Economy | Deniz Appelbaum | Mai., 2017
Designing Continuous Audit Analytics and Fraud Prevention Systems Using Emerging Technologies |  Yunsen Wang |  Mai. 2018
Exploring New Audit Evidence: The Application of Process Mining in Auditing | Tiffany Chiu | Mai. 2018  
Deep Learning Applications in Audit Decision Making |  Ting Sun | Mai. 2018  
Three Essays on Emerging Technologies in Accounting | Feiqi Huang | Jan. 2019  
Three Essays on Audit Innovation: Using Social Media Information and Disruptive Technologies to Enhance Audit Quality |   Andrea M. Rozario | Mai. 2019 
Applying Textual Analysis to Auditing |  Yue Liu | Mai. 2019  
Three Essays on Open Government Data and Data Analytics | Zamil S. Alzamil | Mai. 2019 
Audit Focused Process Mining: The Evolution of Process Mining and Internal Control | Abddulrahman Alrefai | Mai. 2019
Three Essays on the Adoption and Application of Emerging Technologies in Accounting |  Zhaokai Yan | Out. 2019  


**Artigos**

Tembem vale a pena dar uma conferida nos seguintes artigos disponíveis _online_:

* [Embracing the automated audit](https://competency.aicpa.org/media_resources/208730-embracing-the-automated-audit/detail)    
* [The next frontier in data analytics](https://competency.aicpa.org/media_resources/210512-the-next-frontier-in-data-analytics/detail)   
* [Introduction to Data Analysis for Auditors and Accountants](https://www.cpajournal.com/2017/02/16/introduction-to-data-analysis-for-auditors-and-accountants/)    
* [Rethinking the audit](https://competency.aicpa.org/media_resources/211236-rethinking-the-audit/detail)   
* [Audit at a Crossroads](https://www.interfacesymposia.org/I03/I2003Proceedings/AlbrechtConan/AlbrechtConan.paper.pdf)   


**Materiais _online_ diversos**

Listo a seguir alguns materiais que estão disponíveis na internet:

* [Audit Data Analytics - AICPA](https://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/auditanalytics.html)    
* [Audit Analytics - An innovative course at Rutgers](http://raw.rutgers.edu/docs/wcars/26wcars/26WCARS_Presentations/Miklos%20Vasarhelyi/26wcas%20Audit%20Analytics%20courses%20coverage%20introduction%20mav%20(2).pdf)     
* [AUDIT QUALITY THEMATIC REVIEW: THE USE OF DATA ANALYTICS IN THE AUDIT OF FINANCIAL STATEMENTS](https://www.frc.org.uk/getattachment/4fd19a18-1beb-4959-8737-ae2dca80af67/AQTR_Audit-Data-Analytics-Jan-2017.pdf)   
* [Audit Data Standards Python Example](https://github.com/AICPA-AuditDataAnalytics2018/ADS---Python-Example-)    
* [Audit Solution in R- Case Study: Analysis of General Ledger](https://www.rpubs.com/Stewartli/475737)    
* [Audit Solution in R- Case Study: Analysis of Sales/AR](https://www.rpubs.com/Stewartli/486986)    
* [Analytical Procedures in R - Audit Data Analytics (ADA) Use Case](https://www.rpubs.com/Stewartli/451853)    
* [raudit](https://raudit.netlify.app/)    
* [Audit Data Analytics (ADA) - stewartli](https://github.com/stewartli)
* [Data mining your general ledger with Excel](https://www.journalofaccountancy.com/issues/2017/jan/general-ledger-data-mining.html)    
* [Auditinsight](https://auditinsight.com.br/)    
* [Audit Analytics: Data Science for the Accounting Profession](https://github.com/westland/auditanalytics)    
* [Audit Analytics with R - Jonathan Lin](https://auditanalytics.jonlin.ca/)    
* [Audit Analytics: Data Science for the Accounting Profession](https://www.amazon.com.br/Audit-Analytics-Science-Accounting-Profession/dp/3030490904)    
* [Jon Lin - repositório no GitHub](https://github.com/jonlinca/auditanalytics)    

Caso o leitor tenha conhecimento de algum material não elencado neste _post_, pode me encaminhar. Vou atualizando o _post_ à medida que for tomando conhecimento de mais materiais.

Espero que gostem.

Boa leitura!

